name: Docker Image CI

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: "chitanka"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract release version
      id: get_version
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        echo "Found version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.IMAGE_NAME }}
        platforms: linux/amd64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME}}:latest
        push: true
